orangecontrib/timeseries/widgets/owspiralogram.py
Let us write in Linux:
```python
from datetime import datetime
datetime.fromtimestamp(-10000)
datetime.datetime(1969, 12, 31, 22, 13, 20)
```
But the same code fails in Windows:
> OSError [Errno 22] Invalid argument
`try` block and ignore errors.
=> [FIX Spiralogram: do not crash when fromtimestamp raises

.travis.yml, doc/scripting.rst, setup.py
Travis does not work.
Doctests are disabled.
=> [FIX][ENH] Travis

orangecontrib/timeseries/widgets/owseasonaladjustment.py, orangecontrib/timeseries/widgets/tests/test_owseasonaladjustment.py
Widget crashes when gets data which cannot be handled.
Error is shown.
=> [FIX] Seasonal Adjustment: do not fail on negative values

orangecontrib/timeseries/widgets/owtabletotimeseries.py, orangecontrib/timeseries/widgets/tests/test_owtabletotimeseries.py
When we send data to widget **As Timeseries** and produce output and then send bad data to this widget error is shown but output stays the same.
Output set to `None` when error is shown.
=> [FIX] As Timeseries: output None when error

orangecontrib/timeseries/functions.py, orangecontrib/timeseries/widgets/owcorrelogram.py, orangecontrib/timeseries/widgets/tests/test_owcorrelogram.py
Widget crashes when doing interpolation if there is a column with only nans or a column with all nans but one.
Skips interpolation.
=> [FIX] Correlogram: do not crash on a column with nans

orangecontrib/timeseries/widgets/owseasonaladjustment.py, orangecontrib/timeseries/widgets/tests/test_owseasonaladjustment.py
- Widget crashes when there are more periods selected than instances.
- Data has to have at least three instances.
- List of variables is not cleared when there is not data on input.
Maximum periods depends on size of a data
=> [FIX] Seasonal Adjustment: various

orangecontrib/timeseries/widgets/owtabletotimeseries.py, orangecontrib/timeseries/widgets/tests/test_owtabletotimeseries.py
This widget cannot create sequential `time_variabe` if there are no `ContinuousVarible`
in input data.
=> [FIX] As Timeseries: can create sequential time variable and values

orangecontrib/timeseries/__init__.py, orangecontrib/timeseries/datasources.py, orangecontrib/timeseries/tests/test_doctests.py, orangecontrib/timeseries/widgets/owyahoofinance.py, setup.py
Fixes #14 .
TODO:
- ~Remove first commit (`DataFrame` to `Table` function) (waiting https://github.com/biolab/orange3/pull/2836 to be merged).~
- ~Resolution (granularity): remove or fix~ removed
This widget works on only **Orange 3.9 or newer**.
=> [FIX] Yahoo! Finance

orangecontrib/timeseries/functions.py, orangecontrib/timeseries/timeseries.py
Some widgets (**Seasonal Adjustment**, **Moving Transform**, and **Difference**) create `Timeseries` when they get `Table` and they do not set `time_variable`.
Scripting part which creates `time_variable` is now moved from widget **As Timeseries** to `Timeseries`.
Now this code can be used when creating `Timeseries` from `Table`.
=> [FIX] Timeseries: time_variable now created in Timeseries

orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/tests/test_owaggregate.py
**Aggregate** creates 3-dimensional `numpy` metas array. That causes
some other widges (like **Seasonal Adjustment**) to crash.
=> [FIX] Aggregate: do not create 3d metas array

orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/owarimamodel.py, orangecontrib/timeseries/widgets/owcorrelogram.py, orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/owgrangercausality.py, orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/owmodelevaluation.py, orangecontrib/timeseries/widgets/owmovingtransform.py, orangecontrib/timeseries/widgets/owperiodogram.py, orangecontrib/timeseries/widgets/owseasonaladjustment.py, orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/owtabletotimeseries.py, orangecontrib/timeseries/widgets/owtimeslice.py, orangecontrib/timeseries/widgets/owvarmodel.py
Widgets cannot be run independently due to missing datasets.
Some unused imports.
See also #41 .
Unused imports removed.
Unavailable datasets replaced by `airpassengers`.
=> [FIX] Timeseries: use a valid dataset and some cleaning

orangecontrib/timeseries/widgets/owmovingtransform.py, orangecontrib/timeseries/widgets/tests/test_owmovingtransform.py
Connect **File** and **Moving Transform**. Click _Non-overlapping windows_. It has to be checked. Then click _Apply_. The widget crashes.
Do not commit if there are no Transforms selected.
=> [FIX] Moving Transform: prevent crashing when no transforms

orangecontrib/timeseries/widgets/owcorrelogram.py, orangecontrib/timeseries/widgets/tests/test_owcorrelogram.py
**Correlogram** crashes when gets data with less than two instances.
When it gets data with one instance it crashes due to a (possible) bug in `statsmodels`.
```python
x = np.squeeze(np.asarray(x))
```
See: https://github.com/statsmodels/statsmodels/blob/a222cec7c80a608a3213c586e8a71d666f91d60b/statsmodels/tsa/stattools.py#L326
That line returns a `<class 'numpy.ndarray'>` where `x.ndim` is `0`.
And later fails:
```python
n = len(x)
```
https://github.com/statsmodels/statsmodels/blob/a222cec7c80a608a3213c586e8a71d666f91d60b/statsmodels/tsa/stattools.py#L357
Show an error message and do the same when data is `None`.
=> [FIX] Correlogram: at least two instances are required

orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/tests/test_owlinechart.py
Dead code has been causing errors.
List of variables is not emptied when there is no data.
=> [FIX] Line Chart: do not crash on no data

orangecontrib/timeseries/widgets/owgrangercausality.py
Error occurred in #26 .
Old signal name `Timeseries` has been renamed to `Time series`.
Add compatibility.
=> [FIX] Granger Causality: new signals compatibility

orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/tests/test_owspiralogram.py
Widget might crash when new data is sent because of `openContext`. New data might not have `time_variable` and `contextHandler` wants to set `ax1` and `ax2` variables as `monthly`, etc.
~Use `PerfectDomainContextHandler` instead of `ContextHandler`.~
Check if `data` has a `.time_variable`.
Also: Use `VariableListModel` instead of filling combos.
=> [FIX] Spiralogram: do not crash on a new data

orangecontrib/timeseries/widgets/owtabletotimeseries.py, orangecontrib/timeseries/widgets/tests/test_owtabletotimeseries.py
Fixes #51. 
Accept meta attributes in As Timeseries widget.
=> OWTabletoTimeseries: Accept meta attributes

.travis.yml, orangecontrib/timeseries/tests/__init__.py, orangecontrib/timeseries/widgets/tests/test_owtabletotimeseries.py, setup.py
Continuing from https://github.com/biolab/orange3-timeseries/pull/64
@ajdapretnar since I couldn't push to your PR I opened a new one including your commit.
This PR changes:
- Run Travis on Python 3.6 and Python 3.7.
- A test suite is changed to fix the import error.
=> Fix teststs and travis

.travis.yml
Orange no longer supports Python 3.5 and Travis still ran on 3.5.
Run Travis on Python 3.6 and Python 3.7.
=> Test on Py3.6 and Py3.7

setup.py
Implements https://github.com/biolab/orange3-timeseries/issues/62
Statsmodels released new version 0.10.0 which is compatible with Scipy 1.3 so we limit the version to of statsmodels to be at least 0.10.0
=> Change the minimal version for statsmodels

doc/widgets.json
New website requires widgets.json to show docs.
Add widgets.json.
Generated with:
`python ~/orange/orange-hugo/scripts/create_widget_catalog.py --categories "Time Series" --doc .
`
Time Slice missing documentation.
=> Add widgets.json

orangecontrib/timeseries/widgets/owseasonaladjustment.py, orangecontrib/timeseries/widgets/tests/test_owseasonaladjustment.py
Fixes #76.
Replace deprecated concatenate function (which doesn't support axis=1 anymore) with numpy hstack.
=> Seasonal Adjustment: Replace concat with from_numpy

orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/tests/test_owdifference.py
Fixes #75. 
Save selection in OWDifference.
Add tests.
~TODO: Consider moving select_rows to utils in Orange and import from there.~
=> OWDifference: remember selected attributes

doc/scripting.rst, orangecontrib/timeseries/datasources.py, orangecontrib/timeseries/functions.py, orangecontrib/timeseries/tests/test_correlation.py, orangecontrib/timeseries/tests/test_interpolation.py, orangecontrib/timeseries/tests/test_models.py, orangecontrib/timeseries/tests/test_periodogram.py, orangecontrib/timeseries/tests/test_seasonal.py, orangecontrib/timeseries/tests/test_timeseries.py, orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/widgets/_owmodel.py, orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/owarimamodel.py, orangecontrib/timeseries/widgets/owcorrelogram.py, orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/owgrangercausality.py, orangecontrib/timeseries/widgets/owinterpolate.py, orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/owmodelevaluation.py, orangecontrib/timeseries/widgets/owmovingtransform.py, orangecontrib/timeseries/widgets/owperiodogram.py, orangecontrib/timeseries/widgets/owseasonaladjustment.py, orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/owtabletotimeseries.py, orangecontrib/timeseries/widgets/owvarmodel.py, orangecontrib/timeseries/widgets/tests/test_owcorrelogram.py, orangecontrib/timeseries/widgets/tests/test_owlinechart.py, orangecontrib/timeseries/widgets/tests/test_owmodelevaluation.py, orangecontrib/timeseries/widgets/tests/test_owseasonaladjustment.py, orangecontrib/timeseries/widgets/tests/test_owtabletotimeseries.py
#85 
Moved some code from As Timeseries to static functions in `timeseries.py`, so the same code is invoked when using As Timeseries and when connecting Data directly to a timeseries widget.
Timeseries are now always sorted.
NaN values in a continuous attribute that's being used as a time attribute are silently removed in implicit conversion from data table, and coupled with an Information message in the As Timeseries widget.
However, I didn't get the chance to fully test this – Line Chart has been crashing with a TimeoutError for me.
I think the 5 lines at `orangecontrib/timeseries/timeseries.py:23` should be thrown out now that `from_data_table` is more comprehensive, but I left it in (for now), in the interest of backwards compatibility.
=> timeseries: Unify As Timeseries and implicit conversion

orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/util.py, orangecontrib/timeseries/widgets/_rangeslider.py, orangecontrib/timeseries/widgets/owtimeslice.py
=> OWTimeSlice: Spring cleaning

orangecontrib/timeseries/agg_funcs.py, orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/tests/test_owspiralogram.py
Spiralogram fails when TimeVariable is selected and aggregation function is Variance.
Do no cast aggregations as TimeVariables, because they are not.
Probably would be better to not enable certain options for TimeVariable and DiscreteVariable. Count nonzero and Count defined for the former and Mode, Count nonzero and Count defined for the latter.
=> Spiralogram: show aggregated TimeVariable as Continuous

orangecontrib/timeseries/tests/test_timeseries.py, orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/widgets/owtabletotimeseries.py
As Timeseries doesn't consider dates in meta attributes.
Enable support for dates in metas (e.g. Twitter widget puts dates in metas).
Always cast time values as floats.
TODO: tests
=> As Timeseries: support dates in metas

.travis.yml, orangecontrib/timeseries/widgets/owlinechart.py
Fixes https://github.com/biolab/orange3-timeseries/issues/104
Adde a workaround for a Highchart issue. Highchart marks nonpositive values as null when changing to logarithmic and does not un-mark them.
=> [FIX] Line chart: Show zeros after change from logarithmic to linear

orangecontrib/timeseries/widgets/_rangeslider.py, orangecontrib/timeseries/widgets/icons/TimeSlice-pause.svg, orangecontrib/timeseries/widgets/icons/TimeSlice-play.svg, orangecontrib/timeseries/widgets/icons/TimeSlice-step_backward.svg, orangecontrib/timeseries/widgets/icons/TimeSlice-step_forward.svg, orangecontrib/timeseries/widgets/owtimeslice.py
- Standardize handle hitbox
- Rename stuff
- Restrict expansion of control area (Is there an easier way of achieving this?)
I couldn't get the checkboxes to align, and there's more space below the controls within a box than above. With the fixed control area size, this has now become more apparent. I suppose this is an orange-widget-base issue though?
=> [WIP] OWTimeSlice: UX Fixup

orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/widgets/_owmodel.py, orangecontrib/timeseries/widgets/owcorrelogram.py, orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/owgrangercausality.py, orangecontrib/timeseries/widgets/owinterpolate.py, orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/owmodelevaluation.py, orangecontrib/timeseries/widgets/owmovingtransform.py, orangecontrib/timeseries/widgets/owperiodogram.py, orangecontrib/timeseries/widgets/owseasonaladjustment.py, orangecontrib/timeseries/widgets/owspiralogram.py
This should fix #103, but includes some larger changes and should be thoroughly tested before merge.
- Don't detect continuous variables as time variables
- Default to sequential ordering when no time_variable is set
- `self.get_column_view(self.time_variable)[0]` was previously inside a `try: ... except Exception:` block, so this may cause some new errors to pop up (off the top of my head it's a possible cause of #70)
- A `time_attr` kwarg was added to some timeseries constructor functions. By using this kwarg one avoids first detecting a time variable and then setting (possibly the same) another one. Widgets should be rewritten to use this.
- The `__seq__` column was removed, but `time_values` returns the same result as the column previously contained. I.e. `ts.time_variable` does not …
=> timeseries: Refactor

orangecontrib/timeseries/tests/test_timeseries.py, orangecontrib/timeseries/timeseries.py
It could happen that time_variable was set, but was removed from the domain.
Check that time_variable is in domain when constructing Timeseries.
=> Check time_variable in Timeseries.domain

orangecontrib/timeseries/widgets/tests/test_owspiralogram.py
Test failed because of invalid `Context` instance.
Add attributes `attributes` and `metas` to `Context`.
=> OWSpiralogram: Fix broken Context in tests

MANIFEST.in
Fixes #148 (hopefully). 
Add font for Time Slice to MANIFEST. My assumption is that released packages did not include the .ttf file as it was not declared. No error appears on development branches, which would make sense under the assumption.
=> Add TimeSlice icon to MANIFEST

orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/tests/test_owaggregate.py
Aggregate is empty if:
- connect entire data
- remove all features
- add back a subset of features
Change DomainContextHandler to PerfectDomainContextHandler.
=> OWAggregate: Change settings handler to PerfectDomainContextHandler

orangecontrib/timeseries/widgets/owlinechart.py
utcoffset on timevariable is deprecated. 
We replace it with timezone attribute and some logic for conversion
=> Line Chart: replace deprecated utcoffset

doc/conf.py, doc/static/custom.css, orangecontrib/timeseries/widgets/__init__.py, setup.py
While ago we discussed that we will use the same documentation theme for add-ons. After some discussion, we decided on sphinx-rtd-theme. The alternative is Alabaster but its sidebar is not so readable and it breaks long addon names in two lines.
With this PR I am implementing the sphinx-rtd-theme. I also changed that the menu bar collapses on the medium screen already (before it collapsed on small screens). On the medium screen, the content column was narrow already and it works well for widget documentation in Orange since at the default Orange help window size the sidebar is collapsed.
=> Change documentation theme

.github/workflows/test.yml, orangecontrib/timeseries/models.py, orangecontrib/timeseries/tests/test_models.py, setup.py, tox.ini
#177
I tried doing minimal changes to use a non-deprecated implementation. Works, but there is a problem: the results I obtain are different. See the test... Is this expected?
If we can not solve this is quickly I suggest pinning statsmodels <= 0.13 and making a release.
=> [ENH] Use non-deprecated ARIMA implementation

orangecontrib/timeseries/functions.py, orangecontrib/timeseries/tests/test_interpolation.py, orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/widgets/owmodelevaluation.py, orangecontrib/timeseries/widgets/tests/test_owaggregate.py, orangecontrib/timeseries/widgets/tests/test_owcorrelogram.py, orangecontrib/timeseries/widgets/tests/test_owmodelevaluation.py, orangecontrib/timeseries/widgets/tests/test_owseasonaladjustment.py, orangecontrib/timeseries/widgets/tests/test_owtabletotimeseries.py, tox.ini
There have been multiple changes in statsmodels, as well as in Orange, for instance table locking.
Also fixes #196.
- I unlocked tables where necessary: `TimeSeries` was unlockable because it was constructed as a view into an intermediate table
- I increase required Orange version to 3.31 and removed pins (otherwise installation failed due to conflicts)
- argument 'unbiased' in call of `autocorrelation` was removed because it is no longer available; there have been some arguments against "unbiasing" models in this way.
- `freq` has been renamed to `period`; meaning is the same, I've found the `statsmodels`'s commit in which they renamed it
- Model Evaluation contained an invalid fix (#37): if a classifier errored, some function returned a list with 6 "err" strings instead of 7; numpy …
=> Updates for newer dependencies

orangecontrib/timeseries/widgets/_owmodel.py
Base model for VAR and ARIMA did not have a default input and did not name the output tables.
- Set Time series input to BaseModel as default.
- Name the output tables (forecast, fitted values, and residuals).
=> OWBaseModel: Set input and output

orangecontrib/timeseries/functions.py, orangecontrib/timeseries/tests/test_functions.py, orangecontrib/timeseries/widgets/owmovingtransform.py, orangecontrib/timeseries/widgets/tests/test_owmovingtransform.py
Widget is outdated, buggy, occasionally suboptimal.
- Fixes #164: Checkbox to keep or remove the leading instances
- Fixes #181 (can be merged, but will work properly only after merging and releasing https://github.com/biolab/orange3/pull/5990)
- Fixes #182: PR implements new, more efficient functions for moving transforms, hence size should no longer be a problem
- Fixes #184: this should no longer happen in the new implementation
- Implements #88: widget is reorganized. Wrt my proposals, the widget still allows multiple transformations for same variable (one may want to see a min and max, for instances); other changes have been implemented.
**No longer relevant**
- Fixes #88: disable sorting, crash when table is sorted: the widget no longer has such table
**Fixed elsewhere**
- Extra …
=> Moving Transform: Reimplementation

orangecontrib/timeseries/widgets/_owmodel.py, orangecontrib/timeseries/widgets/owarimamodel.py, orangecontrib/timeseries/widgets/owvarmodel.py
Reverts biolab/orange3-timeseries#200. Fixes #206.
We overlooked the comment that #200 requires https://github.com/biolab/orange-widget-base/pull/202, which means it will have to wait for the next version of Orange. We could revert #200 partially, but there is nothing really essential there, so we can revert whole of it.
=> Revert "ARIMA, Var: Minor refactoring and GUI update"

orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/widgets/owtabletotimeseries.py, orangecontrib/timeseries/widgets/tests/test_owtabletotimeseries.py
Fixes #106.
- Problem when the user selected an attribute was caused by a check whether the column contains any nans.
I cannot replicate the bug when using a sequence. Maybe this was already fixed somewhere. @ajdapretnar, please check.
- The second commit updates the widget's code to use
- context settings, with variables instead of strings
- `QGridLayout`, for more accurate spacing
- deferred commit
- `WidgetPreview`
=> As Timeseries: Fix crash on sparse data

.github/workflows/test.yml, orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/tests/test_owlinechart.py, setup.py, tox.ini
Line Chart widget crashes when rolling the cursor over an area that some lines are missing the data (usually the forecast area).
To reproduce, create the following workflow and move the cursor to where the `Air passenger (mean)` is missing
=> [FIX] Line Chart: Fix tooltip for missing line data

orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/widgets/owtabletotimeseries.py, orangecontrib/timeseries/widgets/tests/test_owtabletotimeseries.py, setup.py
- Fixes #239 - reimplementation of `TimeSeries`.
- Also: monkey patch `get_column` into `Table` if necessary, and use `get_column` instead of `get_column_view`.
- Also: Fixes #165 by fixing `Timeseries.from_data_table` and reimplementing `copy` and `__getitem__`.
This changes the previous functionality because it always adds a variable. Should the user have an option to remove it? On the other hand, one could consider previous functionality broken because it allowed constructing a `TimeSeries` with `time_variable == None` (which was in fact unexpected and broke some widgets).
=> [ENH] As Timeseries: Assign time stamps when using implied order

orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/tests/test_owdifference.py
Fixes #244.
It's indeed a minor change, but it may take time to merge because my boss @VesnaT excels at finding my mistakes in exactly these kinds of pull requests.
(Kidding of course. @VesnaT is meticulously great.)
Just to see that I understood this correctly. 
- With first-degree difference, values are just copied -- because zero is subtracted.
- For second degree, the shift is always 1, so there are two lines to be computed. The first is again a copy, and the second is `x1 = (x1 - x0) - (x0 - 0) = x1 - 2 x0`.
When direction is inverted or when computing some kinds of quotients and percentages, this option is disabled.
=> Difference: Add option to assume zero values before

orangecontrib/timeseries/widgets/owcorrelogram.py
@StatViser reported that changing the partial correlation checkbox has no effect.
The widget cached computed correlations using just the attribute - but not also parameters! - as the key. Parameters are now included in the key.
=> Correlogram: Include parameters in cache key

orangecontrib/timeseries/widgets/owarimamodel.py, orangecontrib/timeseries/widgets/tests/test_OWARIMAModel.py
In https://github.com/biolab/orange3-timeseries/pull/235 `Use exogenous data` was removed. I guess it was removed since widget can use them always when they are present on the input and not use them when their input is None. This change didn't remove the `self. use_exog` variable and its use. It can cause an error in model fitting when it is still remembered in Orange's setting as True. The other error is that it is still passed to the model even if it cannot be set.
Remove `self. use_exog` and pass True to the model if exog data on input, False otherwise.
Simple tests.
=> [FIX] ARIMA - remove use_exog

orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/owperiodbase.py, orangecontrib/timeseries/widgets/owspiralogram.py
We don't know which object types are passed to methods for reporting, saving charts and copying to clipboard.
- Added comments with one of the four types handled by `ImgFormat` (`pg.GraphicsItem`, `QGraphicsScene`, `QGraphicsView`, `QWidget`), and the actual derived type, if applicable.
=> Annotate graph_name with graph's types

doc/widgets/moving_transform_w.md, doc/widgets/spiralogram.md, orangecontrib/timeseries/aggregate.py, orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/tests/test_owspiralogram.py
Implements #258.
- Add day of week to `timeseries.PeriodOptions`, which adds it to any widget that uses this list (that is, Spiralogram and Moving Transform)
- Add Day of Week into Spiralogram where it deduces the range from the name
- Fix a wrong tooltip (off by one for day of year/month and week of year)
=> Spiralogram, Moving Transform: Add week of year

orangecontrib/timeseries/aggregate.py, orangecontrib/timeseries/datasources.py, setup.py, tox.ini
- While considering #257, I found that the code can be refactored.
- Aggregation tests are failing since Scipy changed the behaviour of stats functions.
- Refactoring the code of the Datasources module.
- Fix weighted_mode function: Before stats.mode had `keepdims=True` like behaviour by default, which changed in 1.11. Since it is `False,` now the result is a one-dimensional vector, so I removed the part of the code that extracts the first column. I also limited the version of Scipy to >=1.9 since it is the first version offering the `keepdims` parameter.
=> Datasources - Small refactoring

doc/widgets.json, doc/widgets/as_timeseries.md
Hopefully, fixes #254. Even after `make html` the widget did not appear. However, the generated index was ok and was able to search it.
Rename widget.json to appropriate widget name. Fix widget title for Form Timeseries docs.
=> [DOC] Rename As Timeseries to Form Timeseries

orangecontrib/timeseries/functions.py
`ptp` has been removed as array method.
Replace the call with `np.ptp`.
=> Fix Numpy 2.0 compatibility: Replace ndarray.ptp with np.ptp

orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/tests/test_owdifference.py
Fixes #290.
`selection` was not stored properly (now it is) and it was cleared when reinitializing the model (now it's not; I block the signals from selection model).
As a bonus, migration takes care of existing workflows, which should now with correct selections.
=> Time Series: Properly store and restore selection
