biolab/orange3-timeseries

.gitignore, README.md, README.rst
Tentative changes to README with instructions for Anaconda distribution (it works perfectly on Win!).
Added .gitignore (mostly copied from Orange3).
=> Update readme and .gitignore

orangecontrib/timeseries/widgets/_owmodel.py, orangecontrib/timeseries/widgets/_rangeslider.py, orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/owarimamodel.py, orangecontrib/timeseries/widgets/owcorrelogram.py, orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/owgrangercausality.py, orangecontrib/timeseries/widgets/owinterpolate.py, orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/owmodelevaluation.py, orangecontrib/timeseries/widgets/owmovingtransform.py, orangecontrib/timeseries/widgets/owperiodogram.py, orangecontrib/timeseries/widgets/owseasonaladjustment.py, orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/owtabletotimeseries.py, orangecontrib/timeseries/widgets/owtimeslice.py, orangecontrib/timeseries/widgets/owvarmodel.py, orangecontrib/timeseries/widgets/owyahoofinance.py, orangecontrib/timeseries/widgets/utils.py
Replace PyQT4 imports with AnyQt imports
=> Replace PyQt4 imports with AnyQt imports

orangecontrib/timeseries/widgets/owspiralogram.py
@ajdapretnar fixes https://github.com/biolab/orange3-timeseries/issues/16
=> OWSpiralogram: allow inverting Y axis

orangecontrib/timeseries/widgets/owinterpolate.py
=> Interpolate: new signals, default output now interpolated

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/owcorrelogram.py, orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/owmovingtransform.py, orangecontrib/timeseries/widgets/owperiodogram.py, orangecontrib/timeseries/widgets/owseasonaladjustment.py, orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/owtabletotimeseries.py
Iter over `domain` is deprecated. Use iteration over `variables` instead.
=> Iter over variables instead of a domain

orangecontrib/timeseries/widgets/_owmodel.py, orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/owarimamodel.py, orangecontrib/timeseries/widgets/owcorrelogram.py, orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/owgrangercausality.py, orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/owmodelevaluation.py, orangecontrib/timeseries/widgets/owmovingtransform.py, orangecontrib/timeseries/widgets/owperiodogram.py, orangecontrib/timeseries/widgets/owseasonaladjustment.py, orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/owtabletotimeseries.py, orangecontrib/timeseries/widgets/owtimeslice.py, orangecontrib/timeseries/widgets/owyahoofinance.py
Widgets still use old signals.
Upgrade widgets to new signals.
=> [ENH] New signals: all widgets

orangecontrib/timeseries/widgets/owgrangercausality.py
`LinAlgError` might be thrown.
Show an error message.
=> [FIX] Granger Causality: add Numpy Linear Algebra error handling

orangecontrib/timeseries/tests/test_timeseries.py, orangecontrib/timeseries/timeseries.py
Create new `Timeseries.attributes` when changing.
=> [FIX] Timeseries: write into a COPY of attributes

.travis.yml, doc/scripting.rst, orangecontrib/timeseries/functions.py, orangecontrib/timeseries/tests/test_timeseries.py, orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/owspiralogram.py
=> [FIX] Datetime and timestamp conversion on Windows

orangecontrib/timeseries/widgets/owlinechart.py
Plot type changes when variable selection changes.
Keep plot type as selected by the user.
=> Line Chart: keep plot type

.travis.yml, .travis/install_orange.sh
Currently there is not travis test with current Orange master and thus add-on is not tested with newest Orange before release.
Added test case with Orange master
=> Adde test case with Orange master

orangecontrib/timeseries/widgets/owmovingtransform.py
Test were failing because of a new test that check whether all warnings are derived from base class.
Derive warnings, errors, info from base class.
=> Derive warnings from base class

MANIFEST.in, README.pypi, setup.py
It's nice to have a concise description for PyPi that is different to the Github README.
Have two separate READMEs - one for Github and one for PyPi (which is also shown in the add-on dialogue).
=> Provide a separate README for PyPi

orangecontrib/timeseries/functions.py, orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/tests/test_owaggregate.py, orangecontrib/timeseries/widgets/tests/test_owspiralogram.py
Fixes #36. 
Consider timezone in aggregation and pass it in Aggregate and Spiralogram.
Test for Aggregate.
Test for Spiralogram.
Raise error in Spiralogram if data has not TimeVariable (same as in Aggregate).
=> Consider timezone in aggregation

orangecontrib/timeseries/agg_funcs.py, orangecontrib/timeseries/widgets/owaggregate.py, orangecontrib/timeseries/widgets/tests/test_owaggregate.py
Fixes #74. 
Save selection in OWAggregate.
Add tests.
Remove duplicate function from `agg_funcs.py`.
=> OWAggregate: remember selected attributes

orangecontrib/timeseries/widgets/owlinechart.py
Fixes #22 
Added legend to the line chart.
=> LineChart: Add legend.

orangecontrib/timeseries/timeseries.py
First look in attributes, then in metas.
=> timeseries: Find time var in metas

orangecontrib/timeseries/widgets/owdifference.py, orangecontrib/timeseries/widgets/tests/test_owdifference.py
Difference widget can now calculate qoutient between data points.
=> [ENH] Add quotient

orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/owperiodogram.py, orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/owyahoofinance.py
This PR rebases off #95.
I refactored the time delta as a class. It keeps a list of the different timedeltas in the data, exposing the min and max.
Also, I've moved `is_equispaced` to a property in the class. 
I'm not sure what exactly setting `data.is_equispaced = True` in OWYahooFinance did, but I've removed that line after talking with @ajdapretnar about it.
Note: this is a minimal refactor PR, I'll be adding more functionality in #89, rebasing off this branch.
=> Timedelta refactor

orangecontrib/timeseries/widgets/owmovingtransform.py, orangecontrib/timeseries/widgets/tests/test_owmovingtransform.py
Add context settings for Moving Transform.
=> [ENH] Moving transform: Add context settings

setup.py
Timeseries needs more-itertools as a dependency.
Include more-itertools in requirements.
=> Add more-itertools as dependency

orangecontrib/timeseries/widgets/owspiralogram.py, orangecontrib/timeseries/widgets/tests/test_owspiralogram.py
Migrates setting from version 1 to version 2.
Migrate settings for Spiralogram.
Keep the aggregation function if it exists in combo else select default.
=> Spiralogram: migrate settings

orangecontrib/timeseries/functions.py, orangecontrib/timeseries/tests/test_timeseries.py
Tests were failing. How did this ever work?
Properly convert naive datetime and extreme values. Adjust tests.
=> Properly convert between timezones

orangecontrib/timeseries/util.py, orangecontrib/timeseries/widgets/owtimeslice.py
=> OWTimeSlice: Handle numeric time delta

orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/widgets/owtimeslice.py, orangecontrib/timeseries/widgets/tests/test_owtimeslice.py
=> OWTimeSlice: Handle data with one time point

setup.py
Fixes #135. 
Pass explicit encoding parameter.
=> Use utf-8 encoding explicitly

orangecontrib/timeseries/functions.py
Fixes #136 
- changed x value for interpolation from array position to actual time_value.
=> Interpolate data according to time values

setup.py
Fixes #151, #153
Added time slice font to package_data. They were in the package (because of MANIFEST.in), but were never installed.
=> Add Time Slice button icons to package_data

orangecontrib/timeseries/tests/test_models.py, orangecontrib/timeseries/tests/test_seasonal.py, orangecontrib/timeseries/widgets/tests/test_owdifference.py, orangecontrib/timeseries/widgets/tests/test_owseasonaladjustment.py
https://github.com/biolab/orange3/pull/5220
table.domain -> table.domain.variables
=> Enact len(domain) deprecation

orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/tests/test_owlinechart.py
Context didn't correctly store and update settings when features were at the input.
This pull request implements a custom context handler that separately handles features on the input and cases where features are not present.
It fixes: https://github.com/biolab/orange3-timeseries/issues/146, https://github.com/biolab/orange3-timeseries/issues/146, https://github.com/biolab/orange3-timeseries/issues/160
I hope it solves: https://github.com/biolab/orange3-timeseries/issues/166, https://github.com/biolab/orange3-timeseries/issues/161 (cannot reproduce those errors and do not see complete message)
=> Line Chart - update and fix context

orangecontrib/timeseries/widgets/owtimeslice.py
=> owtimeslice: Fixup size policies

setup.py
=> Pin statsmodels < 0.13.0

README.pypi
Fixes #185.
Description referred to ANOVA instead of ARIMA. Fixed.
=> Fix PyPi info: ANOVA -> ARIMA

setup.py
Required version was just tested and not required
=> Require Orange3>=3.31.0 in setup.py

orangecontrib/timeseries/widgets/owaggregate.py
Fixes #175.
**Based on #195.**
Use `gui.deferred` decorator and the corresponding methods for deferred commit.
Also, use `WidgetPreview` for previewing.
=> Aggregate: Fix 'Apply Automatically'

orangecontrib/timeseries/widgets/_owmodel.py, orangecontrib/timeseries/widgets/owarimamodel.py, orangecontrib/timeseries/widgets/owvarmodel.py
ARIMA and VAR widgets were somewhat outdated, gui-wise.
**Requires https://github.com/biolab/orange-widget-base/pull/202 to be released**
Use `WidgetPreview` and deferred apply button. Also use QGridLayout.
I removed hints that belong to documentation.
=> ARIMA, Var: Minor refactoring and GUI update

orangecontrib/timeseries/widgets/owyahoofinance.py
"Fixes #174" by adding a hint about possible bad connection to the error message. That's all we can do here.
Also:
- minor changes to layout
- minor refactoring
- code modernization
=> Yahoo Finance: Cosmetic changes

orangecontrib/timeseries/functions.py, orangecontrib/timeseries/widgets/owinterpolate.py
Interpolate widget has been left alone for too long. 
I updated its code to more up-to-date API, and made some other changes.
=> Interpolate: Facelift

orangecontrib/timeseries/functions.py, orangecontrib/timeseries/widgets/owcorrelogram.py, orangecontrib/timeseries/widgets/owperiodbase.py, orangecontrib/timeseries/widgets/owperiodogram.py, orangecontrib/timeseries/widgets/tests/test_owcorrelogram.py, orangecontrib/timeseries/widgets/tests/test_owperiodogram.py
Widget uses highcharts, which we don't like.
Now it uses pyqtgraph, which we don't like less.
=> Correlogram, Periodogram: Reimplementation in pyqtgraph

orangecontrib/timeseries/widgets/owmodelevaluation.py
Model Evaluation did not use deferred commit.
Model Evaluation uses deferred commit.
=> Model Evaluation: Use deferred commit

orangecontrib/timeseries/widgets/owspiralogram.py
View has empty space. Scene doesn't. Or won't after https://github.com/biolab/orange-widget-base/pull/208
=> Spiralogram: Save/Copy-to-clipboard scene instead of view

orangecontrib/timeseries/widgets/owlinechart.py, orangecontrib/timeseries/widgets/tests/test_owlinechart.py, setup.py
Replace highcharts with pyqtgraph.
Fixes #109, #158, #215
Write the widget from scratch.
=>  Line Chart: Remake

orangecontrib/timeseries/widgets/owlinechart.py
=> [FIX] Line Chart: Plot data in metas

orangecontrib/timeseries/widgets/owtabletotimeseries.py
Fixes https://github.com/biolab/orange3-timeseries/issues/187#issuecomment-1203895004
=> [FIX] As Timeseries: Cast array dtype from object to float

orangecontrib/timeseries/widgets/owlinechart.py
Fixes 2. part of https://github.com/biolab/orange3-timeseries/issues/187#issuecomment-1203895004
=> [FIX] Line Chart: Fix x_data for forecast plotting

setup.py
=> setup: Add pyqtgraph dependency

orangecontrib/timeseries/functions.py
Fixes #219.
Simplify loops, use proper divisor.
=> Granger Causality: Fix progress percentage

orangecontrib/timeseries/functions.py, orangecontrib/timeseries/timeseries.py, orangecontrib/timeseries/widgets/owperiodbase.py, orangecontrib/timeseries/widgets/owperiodogram.py, orangecontrib/timeseries/widgets/tests/test_owperiodogram.py
Fixes #214.
Decide an appropriate unit and scale.
=> Periodogram: Show meaningful tick labels

orangecontrib/timeseries/widgets/_owmodel.py, orangecontrib/timeseries/widgets/owarimamodel.py, orangecontrib/timeseries/widgets/owvarmodel.py, setup.py, tox.ini
Reapplication of #200 .
ARIMA and VAR widgets were somewhat outdated, gui-wise.
**Requires https://github.com/biolab/orange-widget-base/pull/202 to be released**
Use `WidgetPreview` and deferred apply button. Also use QGridLayout.
I removed hints that belong to documentation.
=> [NOMERGE YET] ARIMA, Var: Minor refactoring and GUI update

orangecontrib/timeseries/widgets/_rangeslider.py, orangecontrib/timeseries/widgets/owtimeslice.py
Time slice fails since values are not int on pyqt6
Cast values to int where necessary
=> [FIX] Time Slice - fix PyQt6 incompatibilities

doc/widgets/correlogram.md, doc/widgets/difference.md, doc/widgets/periodogram_w.md, doc/widgets/spiralogram.md
Image names were wrong since #229.
=> Fix image names for case-sensitive architectures

.github/workflows/rebase.yml
Adding automatic rebase workflow
=> CI - Automatic rebase

orangecontrib/timeseries/widgets/tests/test_owspiralogram.py, orangecontrib/timeseries/widgets/tests/test_owtabletotimeseries.py
Tests are not PyQt6 compatible
Fixes for PyQt6 comapitibility
=> PyQt6 compatibility for tests

orangecontrib/timeseries/datasources.py, setup.py
Yahoo Finance does not work (see #256)
import new yfinance module
=> Fix Yahoo Finance Import

.readthedocs.yaml
Read the Docs deprecated the old config files on Sep 25 2023.
Add version 2 of config file.
=> Add basic config file for documentation

.readthedocs.yaml
Config for RTFD not working.
Fix config file.
=> Fix basic config file for documentation

doc/widgets/line_chart.md
Resolves #248.
Add note on pyqtgraph options.
=> [DOC] Line Chart: add note on pyqtgraph options

orangecontrib/timeseries/widgets/owdifference.py
Fixes #288.
Increase the limit to 999 because why not, I guess.
=> Difference: Increase shifting limit to 999
